# Generated by Django 3.2.5 on 2022-04-12 18:01

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Conference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название конференции')),
                ('description', models.CharField(max_length=500, verbose_name='Описание конференции')),
                ('file', models.FileField(max_length=255, upload_to='conferences/', verbose_name='Файл конференции')),
                ('poster', models.ImageField(max_length=255, upload_to='posters/', verbose_name='Постер конференции')),
                ('published_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата публикации конференции')),
                ('views', models.BigIntegerField(default=0, verbose_name='Просмотры')),
                ('slug', models.CharField(max_length=255, verbose_name='Slug')),
            ],
            options={
                'verbose_name': 'Конференция',
                'verbose_name_plural': 'Конференции',
            },
        ),
        migrations.CreateModel(
            name='ConferenceArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название статьи')),
                ('author', models.CharField(max_length=255, verbose_name='Автор статьи')),
                ('keywords_uz', models.TextField(verbose_name='Ключевые слова (на узбекском)')),
                ('annotation_uz', models.TextField(verbose_name='Аннотация (на узбекском)')),
                ('keywords_ru', models.TextField(verbose_name='Ключевые слова (на русском)')),
                ('annotation_ru', models.TextField(verbose_name='Аннотация (на русском)')),
                ('keywords_en', models.TextField(verbose_name='Ключевые слова (на английском)')),
                ('annotation_en', models.TextField(verbose_name='Аннотация (на английском)')),
                ('file', models.FileField(max_length=255, upload_to='conferencearticles/', verbose_name='Файл статьи')),
                ('published_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата публикации статьи')),
                ('views', models.BigIntegerField(default=0, verbose_name='Просмотры')),
                ('slug', models.CharField(max_length=255, verbose_name='Slug')),
                ('conference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='baseapp.conference')),
            ],
            options={
                'verbose_name': 'Статья конференции',
                'verbose_name_plural': 'Статьи конференции',
            },
        ),
        migrations.CreateModel(
            name='Editor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='editors/', verbose_name='3x4 фото')),
                ('name_uz', models.CharField(max_length=255, verbose_name='ФИО редактора (на узбекском)')),
                ('role_uz', models.CharField(max_length=255, verbose_name='Звание редактора (на узбекском)')),
                ('about_uz', models.CharField(max_length=500, verbose_name='О редакторе (на узбекском)')),
                ('name_ru', models.CharField(max_length=255, verbose_name='ФИО редактора (на русском)')),
                ('role_ru', models.CharField(max_length=255, verbose_name='Звание редактора (на русском)')),
                ('about_ru', models.CharField(max_length=500, verbose_name='О редакторе (на русском)')),
                ('name_en', models.CharField(max_length=255, verbose_name='ФИО редактора (на английском)')),
                ('role_en', models.CharField(max_length=255, verbose_name='Звание редактора (на английском)')),
                ('about_en', models.CharField(max_length=500, verbose_name='О редакторе (на английском)')),
            ],
            options={
                'verbose_name': 'Редактор',
                'verbose_name_plural': 'Редакторы',
            },
        ),
        migrations.CreateModel(
            name='Index',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название индекса')),
                ('url', models.CharField(max_length=255, verbose_name='URL индекса')),
                ('logo', models.FileField(upload_to='indexes/', verbose_name='Лого индекса')),
            ],
            options={
                'verbose_name': 'Индекс',
                'verbose_name_plural': 'Индексы',
            },
        ),
        migrations.CreateModel(
            name='Journal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название журнала')),
                ('volume', models.IntegerField(verbose_name='Том журнала')),
                ('issue', models.IntegerField(verbose_name='Номер журнала')),
                ('file', models.FileField(max_length=255, upload_to='journals/', verbose_name='Файл журнала')),
                ('poster', models.ImageField(max_length=255, upload_to='posters/', verbose_name='Постер журнала')),
                ('published_date', models.DateTimeField(verbose_name='Дата публикации журнала')),
                ('views', models.BigIntegerField(default=0, verbose_name='Просмотры')),
                ('slug', models.CharField(max_length=255, verbose_name='Slug')),
            ],
            options={
                'verbose_name': 'Журнал',
                'verbose_name_plural': 'Журналы',
            },
        ),
        migrations.CreateModel(
            name='JournalArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название статьи')),
                ('author', models.CharField(max_length=255, verbose_name='Автор статьи')),
                ('keywords_uz', models.TextField(verbose_name='Ключевые слова (на узбекском)')),
                ('annotation_uz', models.TextField(verbose_name='Аннотация (на узбекском)')),
                ('keywords_ru', models.TextField(verbose_name='Ключевые слова (на русском)')),
                ('annotation_ru', models.TextField(verbose_name='Аннотация (на русском)')),
                ('keywords_en', models.TextField(verbose_name='Ключевые слова (на английском)')),
                ('annotation_en', models.TextField(verbose_name='Аннотация (на английском)')),
                ('file', models.FileField(max_length=255, upload_to='journalarticles/', verbose_name='Файл статьи')),
                ('published_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата публикации статьи')),
                ('views', models.BigIntegerField(default=0, verbose_name='Просмотры')),
                ('slug', models.CharField(max_length=255, verbose_name='Slug')),
                ('journal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='baseapp.journal')),
            ],
            options={
                'verbose_name': 'Статья журнала',
                'verbose_name_plural': 'Статьи журнала',
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Имя')),
                ('email', models.CharField(max_length=255, verbose_name='E-mail')),
                ('subject', models.CharField(max_length=255, verbose_name='Тема')),
                ('detail', models.TextField(verbose_name='Текст сообщения')),
            ],
            options={
                'verbose_name': 'Сообщение',
                'verbose_name_plural': 'Сообщения',
            },
        ),
        migrations.CreateModel(
            name='NewArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_name', models.CharField(max_length=255, verbose_name='ФИО')),
                ('author_phone', models.CharField(max_length=255, verbose_name='Номер телефона')),
                ('name', models.CharField(max_length=255, verbose_name='Название статьи')),
                ('file', models.FileField(max_length=255, upload_to='new_articles/', verbose_name='Файл статьи')),
                ('token', models.CharField(max_length=10, verbose_name='Токен статьи')),
                ('price', models.CharField(max_length=15, verbose_name='Цена статьи')),
            ],
            options={
                'verbose_name': 'Новая статья',
                'verbose_name_plural': 'Новые статьи',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variant', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('waiting', 'Waiting for confirmation'), ('preauth', 'Pre-authorized'), ('confirmed', 'Confirmed'), ('rejected', 'Rejected'), ('refunded', 'Refunded'), ('error', 'Error'), ('input', 'Input')], default='waiting', max_length=10)),
                ('fraud_status', models.CharField(choices=[('unknown', 'Unknown'), ('accept', 'Passed'), ('reject', 'Rejected'), ('review', 'Review')], default='unknown', max_length=10, verbose_name='fraud check')),
                ('fraud_message', models.TextField(blank=True, default='')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('transaction_id', models.CharField(blank=True, max_length=255)),
                ('currency', models.CharField(max_length=10)),
                ('total', models.DecimalField(decimal_places=2, default='0.0', max_digits=9)),
                ('delivery', models.DecimalField(decimal_places=2, default='0.0', max_digits=9)),
                ('tax', models.DecimalField(decimal_places=2, default='0.0', max_digits=9)),
                ('description', models.TextField(blank=True, default='')),
                ('billing_first_name', models.CharField(blank=True, max_length=256)),
                ('billing_last_name', models.CharField(blank=True, max_length=256)),
                ('billing_address_1', models.CharField(blank=True, max_length=256)),
                ('billing_address_2', models.CharField(blank=True, max_length=256)),
                ('billing_city', models.CharField(blank=True, max_length=256)),
                ('billing_postcode', models.CharField(blank=True, max_length=256)),
                ('billing_country_code', models.CharField(blank=True, max_length=2)),
                ('billing_country_area', models.CharField(blank=True, max_length=256)),
                ('billing_email', models.EmailField(blank=True, max_length=254)),
                ('billing_phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None)),
                ('customer_ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('extra_data', models.TextField(blank=True, default='')),
                ('message', models.TextField(blank=True, default='')),
                ('token', models.CharField(blank=True, default='', max_length=36)),
                ('captured_amount', models.DecimalField(decimal_places=2, default='0.0', max_digits=9)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='JournalAuditory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=50, verbose_name='IP зрителя')),
                ('journal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='baseapp.journal')),
            ],
            options={
                'verbose_name': 'Зритель журнала',
                'verbose_name_plural': 'Зрители журнала',
            },
        ),
        migrations.CreateModel(
            name='JournalArticleAuditory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=50, verbose_name='IP зрителя')),
                ('journalarticle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='baseapp.journalarticle')),
            ],
            options={
                'verbose_name': 'Зритель статьи журнала',
                'verbose_name_plural': 'Зрители статьи журнала',
            },
        ),
        migrations.CreateModel(
            name='ConferenceAuditory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=50, verbose_name='IP зрителя')),
                ('conference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='baseapp.conference')),
            ],
            options={
                'verbose_name': 'Зритель конференции',
                'verbose_name_plural': 'Зрители конференции',
            },
        ),
        migrations.CreateModel(
            name='ConferenceArticleAuditory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=50, verbose_name='IP зрителя')),
                ('conferencearticle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='baseapp.conferencearticle')),
            ],
            options={
                'verbose_name': 'Зритель статьи конференции',
                'verbose_name_plural': 'Зрители статьи конференции',
            },
        ),
    ]
