# Generated by Django 3.2.5 on 2022-04-17 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Infoletter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_uz', models.FileField(upload_to='infoletters/', verbose_name='Файл (на узбекском)')),
                ('file_ru', models.FileField(upload_to='infoletters/', verbose_name='Файл (на русском)')),
                ('file_en', models.FileField(upload_to='infoletters/', verbose_name='Файл (на английском)')),
                ('date', models.DateField(verbose_name='Начало месяца')),
            ],
            options={
                'verbose_name': 'Информационное письмо',
                'verbose_name_plural': 'Информационные письма',
            },
        ),
        migrations.AddField(
            model_name='journalarticle',
            name='begin_page',
            field=models.IntegerField(default=0, verbose_name='Страница начала'),
        ),
        migrations.AddField(
            model_name='journalarticle',
            name='end_page',
            field=models.IntegerField(default=0, verbose_name='Страница конца'),
        ),
    ]
