# Generated by Django 3.2.5 on 2022-04-20 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseapp', '0003_auto_20220419_2338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conferencearticle',
            name='author',
            field=models.TextField(verbose_name='Автор статьи'),
        ),
        migrations.AlterField(
            model_name='conferencearticle',
            name='name',
            field=models.TextField(verbose_name='Название статьи'),
        ),
        migrations.AlterField(
            model_name='journalarticle',
            name='author',
            field=models.TextField(verbose_name='Автор статьи'),
        ),
        migrations.AlterField(
            model_name='journalarticle',
            name='name',
            field=models.TextField(verbose_name='Название статьи'),
        ),
    ]
