# Generated by Django 3.2.5 on 2022-04-22 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseapp', '0004_auto_20220420_2326'),
    ]

    operations = [
        migrations.AddField(
            model_name='conferencearticle',
            name='begin_page',
            field=models.IntegerField(default=0, verbose_name='Страница начала'),
        ),
        migrations.AddField(
            model_name='conferencearticle',
            name='end_page',
            field=models.IntegerField(default=0, verbose_name='Страница конца'),
        ),
    ]
